FROM typesense/typesense:0.24.0.rcn15

RUN mkdir -p /tmp/typesense-data

ENV TYPESENSE_DATA_DIR=/tmp/typesense-data
ENV TYPESENSE_API_PORT=$PORT
ENV TYPESENSE_API_KEY=1234

ARG TYPESENSE_API_KEY
ARG TYPESENSE_API_PORT